src/lexer.rs, src/output.rs
`unwrap()` produces panics with no explanation, and on some platforms there are no line numbers in the backtrace even in debug builds (rust-lang/rust#24346). `expect()` with an informative message is a much better user experience.
I didn't convert all instances -- I assume `Regex::new` isn't going to fail since it is used with constants, so I left those. And in a lot of cases the relevant condition is checked -- for instance `if x.contains_key(y) { do_something(x.get(y).unwrap()) }` -- however, these patterns should ideally be refactored to use `match`or other methods to avoid unwrapping.
=> convert some unwrap() to expect(format!(...))

README.md, src/context.rs, src/filters.rs, src/lib.rs, src/output.rs, src/tags/for_block.rs, src/template.rs, src/value.rs, tests/custom_blocks.rs
The iterated-over range is treated as a created-on-the-fly array of
Value instances, and iterated over the same way as an array stored in
a value. This seemed like the least-awful way of doing using the same
code to render both cases.
Also:
* Adds the for_loop helper variables as described in "Liquid for
Designers"
* Adds the notion of a context scope that can be pushed and popped like
a stack frame, which is used to automatically clean up the loop
variables when the loop exits. Implemented as chain of context
objects, with each deferring to a parent if a variable or filter
lookup fails.
* Adds a boolean Value type in an attempt to better mirror Ruby's notion
truthiness
=> Adds for_loop iteration over a range of numbers

README.md, src/context.rs, src/error.rs, src/lexer.rs, src/lib.rs, src/parser.rs, src/tags/assign_tag.rs, src/tags/comment_block.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/mod.rs, src/tags/raw_block.rs, src/token.rs, src/value.rs, tests/custom_blocks.rs
Addresses Issue #14. Another monster pullreq, sorry. 
In addition to adding the `assign` tag, it also
* Adds context::evaluate() to provide a centralized way of interpreting tokens as values, looking up values from the context as necessary. Modelled on the original Ruby source.
* Moves the definition of `Token` from the lexer into its own module to avoid circular imports.
* Adds some constructor functions for liquid::Error to declutter the call site when returning error values
* Adds Result to the tag parser function signature to allow tag parser to signal failure if necessary
* Adds `parser::expect()` to check that a given token appears in the token stream of a parser when you don't actually care about capturing that value,
* Adds an implicit RHS to the condition parser for `If`, so that …
=> Adds assignment tag

src/context.rs, src/lib.rs, src/parser.rs, src/tags/for_block.rs, src/tags/interrupt_tags.rs, src/tags/mod.rs, src/template.rs
Adds the notion of an "interrupt" - a signal in the rendering context that stops all rendering and returns the rendered content back up the call stack. When the stack unwind hits a for_loop, it resets the
interrupt and continues processing as directed - either breaking out of the loop or continuing on to the next iteration.
The `break` and `continue` tags are then implemented on top of this interrupt construct. This is pretty much how the shopify implementation handles the same problem.
Also adds support for nested tags in the parser (e.g. nested `for_loop`, `if`, etc). Prior to this, the parser would truncate the children at the inner `end` tag.
=> Adds `break` and `continue` tags.

src/filters.rs, src/template.rs
* times
* divided_by
* ceil
* floor
* round
=> Add most of the remaining math filters

src/lib.rs, src/parser.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/mod.rs
Adds `unless` support (see #23) to the if_block.rs module. Also adds
support for `elsif` blocks in an `if`, which are parsed into
recursive else blocks.
Also adds a sub-block aware splitter function that can be used to
split a tag body on any of a set of delimiters, where the split is
guaranteed to happen at the top levek of nesting (e.g, attempting
to split the tokens inside an `if` block on an `else` is guaranteed
to split the token stream only on an  `else` block at the same
nesting level as the `if` (as opposed to, say, the `else` block of
a `for_loop` nested inside the body of the `if`).
=> Adds `unless` and `elsif` support

src/lib.rs, src/tags/include_tag.rs, tests/custom_blocks.rs
This allows a user of `liquid-rust` to do the following:
```
let options = LiquidOptions {
blocks: Default::default(),
tags: Default::default(),
relative_path: "tests/fixtures/input".to_owned(),
error_mode: Default::default(),
};
let text = "{% include example.txt %}";
let template = parse(text, options).unwrap();
let mut context = Context::new();
assert_eq!(template.render(&mut context).unwrap(),
Some("5 wot wot\n".to_owned()));
```
This will allow `cobalt.rs` to supply the build path to liquid so the include paths can be more readable and less repetative.
=> Add support for relative paths

src/filters.rs, src/template.rs, tests/filters.rs
This implements the a few more filters.
Specifically it adds:
slice - slice a string. Takes an offset and length, e.g. {{ "hello" | slice: -3, 3 }} #=> llo
References #11
=> Implementing filters for capitalize, downcase, first, last, prepend, append and pluralize

src/filters.rs, src/template.rs, tests/filters.rs
One of the tests is commented out pending fix for comma/space issue: https://github.com/cobalt-org/liquid-rust/issues/41
Otherwise, I think this works based on the other test case I included.
Should probably update https://github.com/cobalt-org/liquid-rust/issues/11 as well.
=> implement split filter

src/filters.rs, src/template.rs, tests/filters.rs
needed to pull in the `itertools` crate since there doesn't
seem to be a good way to do a string join in Rust w/o tons of
code.  I'm open to suggestions for doing this w/o the crate
addition.
Also not a huge fan of the Array validation/unwrapping implementation.
Also open to suggestions.
But it works!
=> implement join filter

Cargo.toml, src/filters.rs, src/lib.rs, src/template.rs
A date filter implementation for #11 from cobalt-org/cobalt.rs#115.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cobalt-org/liquid-rust/42)
=> Add date filter

src/tags/include_tag.rs
This allows for non-string-literals to be given as arguments to the
include tag. This is supported by the Ruby library, and I think it makes
sense to support here too.
=> Allow arguments to include tag to be non-quoted

src/lexer.rs
This allows things like:
{% include my-file.html %}
Previously this example would have produced the tokens:
Identifier("include")
Identifier("my")
Dash
Identifier("file.html")
After this change, the token stream is:
Identifier("include")
Identifier("my-file.html")
This is again something that is supported by the ruby library, which
would be great to support here.
=> Allow dashes in Identifiers

src/tags/for_block.rs
Previously using a "limit" in a for block greater than the length of the
iterable would cause the renderer to panic.
Instead we now check the length of the iterable and if the limit is
greater than the length we pick the whole iterable, otherwise (as
before) slice to the end of the iterable.
=> Prevent panic using limit in for block

src/lib.rs, tests/parse_file.rs
Hey I really like your project and I'm glad to be able to contribute.
If you have any questions about what / why I did something please ask. I'm fairly new to Rust so there are a few '*decisions*' which were really 'I *think* this is how to accomplish that thing I want to do but who knows'.
Implements basic expected functionality:
- Takes as arument a filepath and `LiquidOptions`.
- Returns `Result<Template>`
Includes basics tests (extends `fixtures.rs`).
Includes doc-string documentation.
fixes #57
=> Implement liquid::parse_file(...) method

src/lib.rs
I was reading the docs for parse_file and I realized they were formatted totally incorrectly. I basically ended up adding some whitespace and now it looks a lot better and I tested it locally with `cargo doc`.
Sorry for *yet another* Pull Request, couldn't leave this un-fixed.
=> Fix parse_file(...) docs.

src/filters.rs, src/template.rs
- Template::render(): Sort filter names alphabetically.
- src/filters.rs: Leave a single blank line between function definitions.
=> Sort filters

src/filters.rs, src/template.rs, tests/filters.rs
+ src/filters.rs (sort): Use is_empty() instead of comparing len() with 0.
+ tests/filters.rs: Separate function definitions with a single blank line.
=> Add `modulo' filter

src/lib.rs, src/parser.rs, src/tags/assign_tag.rs, src/tags/capture_block.rs, src/tags/case_block.rs, src/tags/comment_block.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/interrupt_tags.rs, src/tags/raw_block.rs, tests/custom_blocks.rs
This fixes issues with [clippy and lazy_static](https://github.com/Manishearth/rust-clippy/issues/1580).
Also includes adjustments to the new version of clippy.
=> clippy fixes

.travis.yml, Cargo.toml, src/filters.rs, src/lib.rs, src/template.rs
I'm putting all the filters I create from the list in issue #11 here, as they are part of the standard, and the filter in pull request #73 is not.
Let me know if I should merge these two or split all filters into their own pull requests.  Also, note that I'll use this to add more filters, and will leave a note when I've finished adding filters.  If you'd prefer I not work that way, let me know and I'll change it up.
=> New filters

src/filters.rs, tests/filters.rs
According to https://shopify.github.io/liquid/filters/capitalize/, the `capitalize` filter should only capitalize the first character.
=> Only capitalize the first character

src/lexer.rs, tests/whitespace_control.rs
resolves #67
Unit tests added. Shouldn't affect anything outside the lexer. Please confirm / check this.
=> whitespace control

Cargo.toml, src/filters.rs, src/template.rs
I wanted to add a date filter that would allow setting the timezone, so I created this filter based on the date filter.  There is a lot of duplication between this filter and the date filter, but I decided to keep things simple for now.
Example use is: `{{ "13 Jun 2016 12:00:00 +0000" | date_in_tz: "%Y-%m-%d",-13 }}`, which would result in `2016-06-12`.
=> Add `date_in_tz` filter.

Cargo.toml, appveyor.yml, src/error.rs, src/filters.rs, src/lib.rs, src/output.rs, src/tags/capture_block.rs, src/tags/case_block.rs, src/tags/include_tag.rs, tests/custom_blocks.rs, tests/fixtures.rs, tests/multithreading.rs, tests/parse_file.rs
This fixes the test failures.
Note: `truncate` has changed behavior based on an updated version of
unicode-segmentation.
=> chore: upgrade dependencies

.travis.yml, Cargo.toml, appveyor.yml, src/main.rs
This will allow tools like cobalt to dump their intermediate state so both tools can be debugged independently.
=> feat(debug): Adding CLI for testing liquid

Cargo.toml, src/filters.rs, src/lib.rs, src/template.rs
Filters include
- `map`
- `url_encode` and `url_decode`
- `concat`
- `compact` though more of a dummy implementation due to our lack of Nulls
Partially fixes #11.  sort_natural is the only filter remaining.
=> feat(filters): Add missing filters

src/filters.rs, src/main.rs, src/template.rs
=> feat(filters): Add sort_natural

src/lib.rs, src/main.rs, src/tags/include_tag.rs, tests/custom_blocks.rs
Hello! 
This is my first Rust contribution, so I expect it to be less-than-perfect, please let me know how I can improve it!
---
Currently `LiquidOptions.file_system` is implemented as a `PathBuf`, reading directly for the disk. This leaves little options for where to store the files. I'd like to have my files in abstract repositories, either in the database, S3, etc. As a result, I changed `file_system` to be a trait, boxed in `LiquidOptions`. 
Then I realized my custom blocks needed a way to specify to the file system where the templates were stored. This required little change, but I still thought it would be a good time to introduce a `TemplateName` type. I wondered if I should change `include_tag` to send `include://#{path}` as the `TemplateName`, like I would do in custom blocks, …
=> File system trait and template locations

src/output.rs, src/parser.rs
I was trying to implement named arguments for filters, and I had trouble understanding what `VarOrVal` meant. I understood that it could contain either a variable or a value, but understanding the union of those types was hard.
It occurred to me that holding these values is just a coincidence; what `VarOrVal` really represents, is the arguments passed into filters [as used in FilterPrototype](https://github.com/cobalt-org/liquid-rust/compare/master...gmalette:rename-varorval-to-argument?expand=1#diff-ac5cd937cc00cb0544b06a1b6ce1ce5eR10). It's the "unknown" value of an argument between the time the code gets parsed until it gets evaluated.
Thoughts about renaming it `FilterArgument` ?
Had the grammar been structured different, I would've suggested something more along the lines of
```rust …
```
=> refactor(Parse): Rename VarOrVal to Argument

CONTRIBUTING.md, benches/liquid.rs
These are based on Tera and Handlebars. shopify/liquid's are a bit more
work to port over.
The process for running this has been documented in `CONTRIBUTING.md`,
along with a lot of other things.
=> feat(performance): Add benchmarks

.travis.yml
- Hopefully `cargo coveralls` from `cargo-travis` will fix #107
- rustfmt is now stable-only to reduce overall build time
- Do test build of docs.  Eventually we'll also want to setup upload
- Enable `bench`
=> fix(CI): Switch to `cargo-travis`

src/context.rs
=> fix: Remove `Box` from interface for clippy

src/filters.rs, src/value.rs, tests/value.rs
This adds the missing null type to the values of liquid, thus allowing to
parse serde_json and others containing null-values in the data directly
=> feat(value): Add null value

src/filters.rs, src/lexer.rs, src/lib.rs, src/parser.rs, src/path.rs
This fixes #127 adding feature to access identifiers via index
- array indexes `arr[0]` are supported
- object indexes `obj["child"]` are supported and interchangeable with `obj.child`
- index expressions are not yet supported.
Checklist
=> Add indexed access to context values

README.md, src/lib.rs, src/parser.rs, tests/custom_blocks.rs
This required making `ParseBlock` (formerly `Block) and `ParseTag` (formerly `Tag`) cloneable.
Obviously, this breaks compatibility in multiple ways.  This is needed for a cobalt feature which will consolidate the creation of `LiquidOptions` but it still needs to be cloneable because `liquid::parse` takes ownership.
This is a tiny steps towards #95
=> feat: Make LiquidOptions cloneable

src/parser.rs, src/tags/if_block.rs, src/template.rs, src/value/values.rs
In cobalt, this presented itself as `{if null_var}` evaluating as true.
Its sad we missed this case considering we added code for `Nil` right
before a comment about us not supporting `Nil`.
=>  fix(nil): Equality logic missed a case 

src/tags/if_block.rs
This will panic if either side of the operator cannot be evaluated as a string.
It works for both variables and string literals as expected.
=> Implement `contains` operator

.travis.yml, Cargo.toml, appveyor.yml, src/filters/date.rs, src/filters/mod.rs, src/lib.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/value/values.rs
=>  feat(Value): Control key order 

src/tags/if_block.rs, src/value/values.rs
A couple releases ago, I made liquid consistently treat non-existent
variables as a hard error.
To help with checking for variable existence, `contains` operator was
finally implemented.  That doesn't help with globals though.
So to support globals, I'm relaxing the non-existence restrictions
within a unary-if.
ie you can now do
```
{% if title %}
{{ title }}
{% endif %}
```
Fixes cobalt-org/cobalt.rs#363
=> feat(if): Base if is an existence check

.travis.yml, appveyor.yml
=> chore: Limit CI to master

README.md, src/compiler/lexer.rs, src/compiler/token.rs, src/filters/date.rs, src/filters/html.rs, src/filters/math.rs, src/filters/mod.rs, src/interpreter/context.rs, src/lib.rs, src/parser.rs, src/tags/capture_block.rs, src/tags/case_block.rs, src/tags/cycle_tag.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/include_tag.rs, src/value/scalar.rs, src/value/values.rs, tests/filters.rs, tests/fixtures.rs, tests/multithreading.rs, tests/parse_file.rs, tests/value.rs
BREAKING CHANGE: Liquid's "Value" API now works with f64's instead of f32's
=> Upgrade to f64 floats

src/lib.rs, src/value/scalar.rs
=> Expose `{{  "now" | date "%Y" }}` for carg-generate

src/interpreter/context.rs, src/parser.rs, src/tags/for_block.rs, src/tags/include_tag.rs, src/template.rs
Before
test bench_parse_template  ... bench:      25,960 ns/iter (+/- 2,495)
test bench_parse_text      ... bench:         854 ns/iter (+/- 60)
test bench_parse_variable  ... bench:       2,802 ns/iter (+/- 241)
test bench_render_template ... bench:       8,106 ns/iter (+/- 578)
test bench_render_text     ... bench:         456 ns/iter (+/- 29)
test bench_render_variable ... bench:       1,617 ns/iter (+/- 117)
After:
test bench_parse_template  ... bench:      25,607 ns/iter (+/- 2,131)
test bench_parse_text      ... bench:         624 ns/iter (+/- 43)
test bench_parse_variable  ... bench:       2,600 ns/iter (+/- 221)
test bench_render_template ... bench:       7,817 ns/iter (+/- 554)
test bench_render_text     ... bench:         262 ns/iter (+/- 18)
test bench_render_variable ... bench: …
=> perf: Reduce allocations

src/compiler/parser.rs, src/interpreter/output.rs, src/interpreter/renderable.rs, src/interpreter/template.rs, src/interpreter/text.rs, src/interpreter/variable.rs, src/tags/assign_tag.rs, src/tags/capture_block.rs, src/tags/case_block.rs, src/tags/comment_block.rs, src/tags/cycle_tag.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/include_tag.rs, src/tags/interrupt_tags.rs, src/tags/raw_block.rs, src/template.rs
`render_to` uses an `io::Write`.  This is hopefully better than string
concatenation, especially if you can write directly to file. `render` is
still available for convinience (though it no longer returns an
`Option`).
Fixes #187
BREAKING CHANGES: Changed focus to `io::Write`
- `Renderable`s must implement `render_to`.
- `render` no longer returns an `Option`.
=> perf(render): Use a Write

src/compiler/token.rs, src/filters/mod.rs, src/value/scalar.rs
The benchmarks come back as a wash.  The benchmarks don't exercise this
case (ie see the benefit) so this means we aren't worse off then before.
BREAKING CHANGE: Any `str` passed in must have `&'static` lifetime.
=> perf(value): Support str's

src/compiler/include.rs, src/compiler/lexer.rs, src/compiler/token.rs, src/filters/math.rs, src/filters/mod.rs, src/interpreter/argument.rs, src/interpreter/context.rs, src/interpreter/mod.rs, src/interpreter/output.rs, src/interpreter/renderable.rs, src/interpreter/template.rs, src/interpreter/text.rs, src/interpreter/variable.rs, src/tags/assign_tag.rs, src/tags/capture_block.rs, src/tags/case_block.rs, src/tags/comment_block.rs, src/tags/cycle_tag.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/include_tag.rs, src/tags/interrupt_tags.rs, src/tags/raw_block.rs, src/template.rs, src/value/values.rs
This is an attempt to modularize Context's logic while allowing for future evolution without breaking anyone.
The concern of breaking people is why traits aren't used.   Instead, independently accessibly pieces that hide what state is needed for each
Future work:
- Making globals a trait.
Potential future work:
- Switching the stack and interrupt state to a reference struct approach like CycleState
- Possibly going more of an ECS approach with decoupled systems, removing tag-specific knowledge from the interpreter
=> Modularize Context

src/interpreter/context.rs, src/interpreter/globals.rs, src/interpreter/mod.rs, src/template.rs
Part of #95
Before
test bench_parse_template  ... bench:      27,407 ns/iter (+/- 11,395)
test bench_parse_text      ... bench:         638 ns/iter (+/- 46)
test bench_parse_variable  ... bench:       2,479 ns/iter (+/- 212)
test bench_render_template ... bench:       8,046 ns/iter (+/- 2,514)
test bench_render_text     ... bench:         344 ns/iter (+/- 23)
test bench_render_variable ... bench:       1,578 ns/iter (+/- 243)
After
test bench_parse_template  ... bench:      26,348 ns/iter (+/- 4,703)
test bench_parse_text      ... bench:         653 ns/iter (+/- 169)
test bench_parse_variable  ... bench:       2,647 ns/iter (+/- 187)
test bench_render_template ... bench:       6,898 ns/iter (+/- 1,526)
test bench_render_text     ... bench:         276 ns/iter (+/- 28)
test …
=> fix(perf): Don't clone globals

src/tags/for_block.rs
Not the fastest implementation but it will do for now.
Fixes #201
=> feat(for-block): Support iterating on Object

.travis.yml, liquid-compiler/src/parser.rs, liquid-interpreter/src/variable.rs, liquid-value/src/index.rs, liquid-value/src/path.rs, src/tags/assign_tag.rs
This does not fix it so the filter arguments support indexing.
Fixes #207
Note: This touches
- liquid-value
- liquid-interpreter
- liquid-compiler
- liquid
=> feat(filters): Allow the input to index

liquid-compiler/src/lexer.rs, liquid-compiler/src/token.rs, src/tags/if_block.rs
Implement disjunction and conjunction operators to if and unless blocks, as documented in the [shopify help center](https://help.shopify.com/en/themes/liquid/tags/control-flow-tags#multiple-conditions-and-or).
=> feat(if_block): support multiple conditions with `and` and `or`

liquid-value/src/values.rs
Allows the use of `.first` and `.last` on arrays in order to get, respectively, the first or the last element.
=> feat(array): indexing with `.first` and `.last`

liquid-interpreter/src/variable.rs, src/tags/for_block.rs, src/template.rs
Taking care of ideas from #234 all except changing stack frames.
tl;dr we are now competitive with Tera.  On some (bigtable), we are slower.  On a lot of others (bigobject), we are a lot faster.
Before
```
Running target/release/deps/handlebars_baseline-7bc95501ed86afa7
running 3 tests
test large_loop_helper ... bench:   4,688,450 ns/iter (+/- 418,530)
test parse_template    ... bench:      31,014 ns/iter (+/- 2,958)
test render_template   ... bench:      34,726 ns/iter (+/- 2,384)
test result: ok. 0 passed; 0 failed; 0 ignored; 3 measured; 0 filtered out
Running target/release/deps/handlebars_liquid-9a990ffdd1daf4b0
running 3 tests
test large_loop_helper ... bench:   1,503,200 ns/iter (+/- 205,392)
test parse_template    ... bench:      36,345 ns/iter (+/- 2,511)
test render_template …
```
=> Low hanging fruit for performance

liquid-interpreter/src/context.rs, liquid-interpreter/src/filter_chain.rs
BREAKING CHANGE: `Context::get_filter` now returns `Result`.
=> fix(errors): List alternative filters

.gitattributes
When checking out the master branch of liquid-rust on Windows, a number of unit tests were failing due to line-ending differences.
This PR makes Windows users check out the Rust and text files in the depot with Unix line endings to avoid such issues.
=> Windows line endings

src/tags/case_block.rs
The test still doesn't pass because of using `null`.
fixes #279
=> feat(case_block): support comma separated values in `when`

tests/conformance_ruby/blank_test.rs, tests/conformance_ruby/capture_test.rs, tests/conformance_ruby/error_handling_test.rs, tests/conformance_ruby/filter_test.rs, tests/conformance_ruby/output_test.rs, tests/conformance_ruby/parsing_quirks_test.rs, tests/conformance_ruby/standard_filter_test.rs, tests/conformance_ruby/tags/for_tag_test.rs, tests/conformance_ruby/tags/if_else_tag_test.rs, tests/conformance_ruby/tags/include_tag_test.rs, tests/conformance_ruby/tags/increment_tag_test.rs, tests/conformance_ruby/tags/raw_tag_test.rs, tests/conformance_ruby/tags/standard_tag_test.rs, tests/conformance_ruby/tags/statements_test.rs, tests/conformance_ruby/tags/table_row_test.rs, tests/conformance_ruby/tags/unless_else_tag_test.rs, tests/conformance_ruby/template_test.rs, tests/conformance_ruby/variable_test.rs
- Switched almost all `ignore` to `should_panic` so when someone fixes a test, it'll yell at them
- Found a lot of my `ignore`s were fixed when rebasing against the new parser! Thanks @Goncalerta !
=> tests: Annotate incompat with issues

liquid-interpreter/src/context.rs, liquid-interpreter/src/stack.rs, src/tags/include_tag.rs
The goal of this is so that runtime includes of partials can set this
and then any error (usually the `trace`) that happens within that partial can be prefixed with
the name.  Eventually we also want these to include line numbers (see #247).
In the end, this will make the errors look more like what you'd expect
from a compiler error.
=> feat(interpreter): Allow named stack frames

src/filters/html.rs
Not every "char" is just one byte wide. Enumerating `chars()` will lead
to off-by-one (or more) errors with wider characters (e.g. ¹), it could
even panic when accessign a subslice (`&s[last..i]`).
=> Iterate by proper char indices

liquid-compiler/src/grammar.pest, liquid-compiler/src/parser.rs, src/tags/comment_block.rs, src/tags/raw_block.rs, tests/conformance_ruby/tags/raw_tag_test.rs, tests/conformance_ruby/tags/standard_tag_test.rs
Fixes #277 
I don't really like this fix as it is a bit messy, but I guess it gets to do its job, so I think we can consider it even if only as a temporary fix, until we find a better way to handle this issue.
What motivated me into having this fixed was that @Geobert and @epage run into this issue, as reported in #320 and #277 , which means that there might be some urgency in getting this at least working.
Blocks will now be free to parse whatever inside them without liquid restrictions, using `escape_liquid` method. This means invalid liquid will be accepted by `{% raw %}` and `{% comment %}`, as well as any future block that wishes to override liquid rules.
This works by creating a new rule, `LaxLiquidFile`, which instead of directly raising any errors, it produces `InvalidLiquid` …
=> fix(parser): blocks can accept invalid liquid

liquid-value/src/date.rs, liquid-value/src/lib.rs, liquid-value/src/scalar.rs, src/filters/extra/date.rs, tests/derive_macros.rs
BREAKING CHANGE: `Date` and `DateTime` are now newtypes.
=> refactor(value): Use a newtype for Date/DateTime

crates/kstring/src/cow.rs, crates/kstring/src/fixed.rs, crates/kstring/src/ref.rs, crates/kstring/src/string.rs
The main ones
- Shortened the debug reprs.  We don't make it the same as a `str` because we want enough info to know what optimizations are being applied
- Add a `From` that I found useful
- Ensure fixed strings are used with serde
=> Misc kstring improvements

crates/core/src/model/scalar/mod.rs, crates/kstring/src/cow.rs, crates/kstring/src/string.rs
This is my second attempt at this, it replaces https://github.com/cobalt-org/liquid-rust/pull/411
=> Introduces into_cow_str for KStringCow, KString, and ScalarCow

crates/core/src/model/array/mod.rs, crates/core/src/model/find.rs, crates/core/src/model/object/mod.rs, crates/core/src/model/scalar/mod.rs, crates/core/src/model/scalar/ser.rs, crates/core/src/model/value/cow.rs, crates/core/src/model/value/ser.rs, crates/core/src/model/value/values.rs, crates/core/src/model/value/view.rs, crates/core/src/parser/parser.rs, crates/derive/src/filter_parameters.rs, crates/derive/src/lib.rs, crates/derive/src/object_view.rs, crates/lib/src/extra/date.rs, crates/lib/src/jekyll/include_tag.rs, crates/lib/src/shopify/pluralize.rs, crates/lib/src/stdlib/blocks/for_block.rs, crates/lib/src/stdlib/filters/math.rs, crates/lib/src/stdlib/filters/mod.rs, crates/lib/src/stdlib/filters/string/truncate.rs, crates/lib/src/stdlib/tags/include_tag.rs, tests/derive_object.rs
Pros:
- More general
- Integrates better with SQL
- Doesn't increase `Scalar`size because there are larger types
Cons
- Doesn't fit within an f64.
=> fix(value)!: Use i64 rather than i32

CHANGELOG.md, crates/core/src/model/scalar/date.rs, crates/core/src/model/scalar/datetime.rs
When I ported this code from cobalt to liquid, I missed that I was using
serialziation methods on the underlying type rather than our own.
=> fix(model): DateTime serialization was off

crates/lib/src/stdlib/blocks/for_block.rs, tests/conformance_ruby/tags/for_tag_test.rs
PR for this issue: https://github.com/cobalt-org/liquid-rust/issues/271
I copied two tests from the conformance test suite and one of them I modified as it seems that `Value::Nil` works slightly different.
=> Feat: Added 'parentloop' varaible to 'forloop' for the standard lib

crates/lib/src/jekyll/include_tag.rs, crates/lib/src/stdlib/tags/include_tag.rs, tests/conformance_ruby/tags/include_tag_test.rs
This adds it both for Jekyll and Liquid versions of include which have different syntaxes.
Fixes #310
=> feat(lib): support for variable passing for `include`

crates/core/src/parser/parser.rs
This PR makes changes to `TagBlock` so that it checks ending tags against the block's `BlockReflection::end_tag()` instead of `end<name>` where `<name>` is the tag name the block plugin was registered under.
This PR also changes `TagBlock` so that it compares starting tags in nested `escape_liquid` blocks against `BlockReflection::start_tag()` instead of the tag name the block plugin was registered under. Block plugins are normally registered under their `BlockReflection::start_tag()` value, but anything registering block plugins under a different name than the block's `start_tag()` value will experience strange behavior.
This PR also adds unit tests to `parser.rs` that check to make sure both `<name>`-`end<name>` and non-`<name>`-`end<name>` block tags parse as expected. These tests are …
=> fix(liquid-core)!: allow block tags not in the `<name>`-`end<name>` format

README.md
The README mentions to add `liquid = "0.20"` to Cargo.toml but the current crate version is 0.23.1
=> Update crate version mentioned in README

crates/core/src/model/scalar/date.rs, crates/core/src/model/scalar/datetime.rs
PR #460 removed a lot of chrono helpers that cobalt was relying on.  This adds them back in.
=> fix(date): Add back support from before time

crates/core/src/model/scalar/datetime.rs
Closes #493 
To sum up, the problem describe on the issue is the following:
* Variables get serialized, in particular, datetime variables were being serialized with the following format:
```
const DATE_TIME_FORMAT: &[time::format_description::FormatItem<'static>] = time::macros::format_description!(
"[year]-[month]-[day] [hour]:[minute]:[second] [offset_hour sign:mandatory][offset_minute]"
);
```
This format format doesn't include the subsecond component, so when a variable was being serialized, the subseconds were lost.
This PR introduces a new format for serialization and uses it for that purpose:
```
const DATE_TIME_FORMAT_SUBSEC: &[time::format_description::FormatItem<'static>] = time::macros::format_description!(
"[year]-[month]-[day] [hour]:[minute]:[second].[subsecond] [offset_hour …
```
=> Support millisecond precision on date variables

crates/core/src/parser/filter.rs, crates/core/src/runtime/stack.rs, crates/derive/src/lib.rs, crates/lib/src/stdlib/blocks/for_block.rs, crates/lib/src/stdlib/blocks/mod.rs, crates/lib/src/stdlib/mod.rs, crates/lib/src/stdlib/tags/mod.rs, crates/lib/src/stdlib/tags/render_tag.rs, src/parser.rs, tests/conformance_ruby/tags/mod.rs, tests/conformance_ruby/tags/render_tag_test.rs, tests/test_helper.rs
The main functionality missing is `as <name>` should be optional,
defaulting to the partial's file name.
For background, see
- https://shopify.dev/docs/api/liquid/tags/render
- https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/render.rb
- https://github.com/Shopify/liquid/blob/master/test/integration/tags/render_tag_test.rb
Fixes #471
=> feat: Add render tag

crates/core/src/parser/parser.rs, crates/lib/src/jekyll/array.rs, crates/lib/tests/conformance_jekyll/mod.rs, crates/lib/tests/conformance_jekyll/test_filters.rs
Part of #311.  Continuation of #546
=> feat(lib): Implement Jekyll's version of sort

crates/core/src/model/scalar/datetime.rs
Adds UNIX timestamp parsing capabilities to the `date` filter, implemented according to the behavior described in https://github.com/cobalt-org/liquid-rust/issues/48#issuecomment-354367081. The main purpose of this feature is to allow basic arithmetic operations on datetime values, e.g. `{{ "today" | date: "%s" | minus: 86400 | date: "%Y-%m-%d" }}` to display yesterday's date.
=> feat(core): Add support for unix timestamps in datetime parsing

README.md
I was trying out this crate and noticed a little typo.
=> docs(README) Correct typo "suite" -> "suit"
