cobalt-org/liquid-rust

src/lib.rs
Allow an easier creation of custom tags.
=> Add public visibility to parser::parse

README.md, src/context.rs, src/error.rs, src/filters.rs, src/lexer.rs, src/lib.rs, src/output.rs, src/parser.rs, src/template.rs, src/variable.rs, tests/custom_output/mod.rs, tests/filters.rs, tests/simple/mod.rs
- Allow filter arguments
- Add filters: upcase, minus, replace
- Filter can now work with Value type and not only raw str ( allow filter on arrays, objects, etc )
- changes 100% tested
=> Great filters improvement

src/filters.rs, src/template.rs, tests/filters.rs
=> Adding Plus filter

src/lib.rs, src/tags/capture_block.rs, src/tags/mod.rs
Implements the capture block for #21.
Finally, a sane pull request of reasonable size! :-)
=> Adds capture block

src/tags/include_tag.rs, tests/fixtures/input/include.txt, tests/fixtures/input/include_with_context.txt
Fixes #31. Still need to figure out variable part and if we want to include it.
=> Moved include tag to String Literal

src/context.rs, src/lib.rs, src/parser.rs, src/tags/cycle_tag.rs, src/tags/if_block.rs, src/tags/mod.rs
Adds cycle tag, as per Issue #13.
=> Adds cycle

src/context.rs, src/template.rs
This allows for users to override the default filters.
=> Only add default filters if not already set

src/tags/include_tag.rs
=> fix appveyor tests

src/filters.rs, src/lib.rs, src/parser.rs, src/template.rs, src/value.rs, tests/filters.rs
Hi.
- Implemented PartialEq correctly and completely, as it was asked in TODO 
- Added Eq and Ord for Value
- Made `sort` filter with test
=> Value traits and sort filter

src/tags/for_block.rs
=> Move to `forloop` in preference to `for_loop`

src/filters.rs
src/filters.rs (check_args_len): New function.
=> [refactoring] Use a function to check the number of arguments

src/filters.rs, src/template.rs, tests/filters.rs
=> Add remove_first, remove, replace_first filters, strip_html and truncatewords

.travis.yml, appveyor.yml, src/context.rs, src/filters.rs, src/lib.rs, src/output.rs, src/parser.rs, src/tags/case_block.rs, src/tags/for_block.rs, tests/custom_blocks.rs, tests/filters.rs, tests/parse_file.rs
I already made similar changes in Cobalt (https://github.com/cobalt-org/cobalt.rs/pull/176). This greatly improves build speed (even more so than in Cobalt because we don't build for OSX here) and stability. It also fixes the code coverage reporting.
=> Refactor CI

src/filters.rs, src/template.rs, tests/filters.rs
More to come. It's not covered in #74 and missing in #11 (see my comment there).
Mimics behavior from the [shopify implementation](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L356)
=> add default filter

Cargo.toml, src/filters.rs, src/lib.rs, src/value.rs
feat(value): Add convenience functions
The idea is based off of the `toml` crate.  It helps in `filters.rs` to draw attention to the business logic.
=> feat(value): Add convinience functions

Cargo.toml, src/context.rs, src/lib.rs, src/value.rs, tests/value.rs
This should open it up for clients to easily serialize to/from the formats
they care about.
=> feat(value): Add serde support

.travis.yml, appveyor.yml, src/error.rs, src/filters.rs, src/lexer.rs, src/main.rs, src/output.rs, src/parser.rs, src/tags/assign_tag.rs, src/tags/capture_block.rs, src/tags/comment_block.rs, src/tags/cycle_tag.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/interrupt_tags.rs, src/tags/raw_block.rs, src/template.rs, src/value.rs, tests/custom_blocks.rs, tests/filters.rs, tests/fixtures.rs, tests/multithreading.rs, tests/parse_file.rs, tests/value.rs
Either corrects filters to align with shopify/liquid or notes the differences.
=> fix(filters): Align with shopify/liquid's filters

src/filters.rs
=> feat(filters): `round` accepts a precision param

.travis.yml, appveyor.yml
This tries to hack around #110 while making the CI easier to maintain.
=> Improve CI's stability, debugability, and alignment with `trust`

.travis.yml
=> style(CI): Clean up using cargo-when

src/compiler/parser.rs, src/tags/raw_block.rs
=>  fix(raw): Stop swapping the text's order 

src/filters.rs
This is a small step to #48 for the purpose of supporting cobalt
changing its format.
=> feat(filters): date can parse YYYY-MM-DD HH:MM:SS TTTT

src/lib.rs, src/value/mod.rs, src/value/scalar.rs
=> Make the API a bit easier to work with

.travis.yml, Cargo.toml, README.md, appveyor.yml, build.rs, tests/skeptic.rs
=>  fix: Reduce deps for users

README.md, src/interpreter/context.rs, src/lib.rs, src/parser.rs, src/tags/assign_tag.rs, src/tags/capture_block.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/value/values.rs, tests/filters.rs, tests/fixtures.rs, tests/parse_file.rs, tests/value.rs
=> Changed Object to use Cow<str> instead of String

src/filters/math.rs, src/filters/mod.rs, src/parser.rs
Added two filters and unit tests for them:
* [at_least](https://shopify.github.io/liquid/filters/at_least/)
* [at_most](https://shopify.github.io/liquid/filters/at_most/)
=> Add filters: "at_least" and "at_most".

src/tags/for_block.rs, src/tags/interrupt_tags.rs
For loops with ranges should include the last value.
=> fix(for_block): make ranges inclusive.

src/tags/for_block.rs
Make forloops and tablerows support variables in their parameters (`offset`, `limit`, `cols`).
Closes #162
=> feat(for_block): support parameters with variables

src/tags/for_block.rs
Similar to forloop object, but for tablerow.
=> feat(tablerow): add tablerow object for its tag

liquid-compiler/src/grammar.pest, tests/conformance_ruby/tags/standard_tag_test.rs, tests/conformance_ruby/variable_test.rs
=> feat(parser): accept newlines as `WHITESPACE`

src/tags/if_block.rs, tests/conformance_ruby/tags/unless_else_tag_test.rs
=> feat(unless_block): support `else`

liquid-compiler/src/grammar.pest, liquid-compiler/src/parser.rs, liquid-value/src/lib.rs, liquid-value/src/macros.rs, liquid-value/src/values.rs, src/tags/for_block.rs, tests/conformance_ruby/tags/for_tag_test.rs, tests/conformance_ruby/tags/if_else_tag_test.rs, tests/conformance_ruby/tags/standard_tag_test.rs, tests/conformance_ruby/tags/statements_test.rs, tests/conformance_ruby/variable_test.rs
=> Support nil, null, empty, and blank literals

.travis.yml, liquid-compiler/src/filter_chain.rs, liquid-interpreter/src/expression.rs, liquid-interpreter/src/store.rs, liquid-interpreter/src/variable.rs, liquid-value/src/path.rs, liquid-value/src/scalar.rs, liquid-value/src/values.rs, src/filters/array.rs, src/filters/html.rs, src/filters/mod.rs, src/tags/case_block.rs, src/tags/cycle_tag.rs, src/tags/for_block.rs, tests/conformance_ruby/filter_test.rs, tests/conformance_ruby/output_test.rs, tests/conformance_ruby/standard_filter_test.rs
=> fix(error): look of values/variables

src/lib.rs
=> feat(error): liquid re-export all error stuff

liquid-compiler/src/parser.rs, liquid-error/src/error.rs, liquid-interpreter/src/store.rs, src/filters/mod.rs, src/tags/cycle_tag.rs, src/tags/for_block.rs
=> feat(error): Streamline with into_err

liquid-value/src/scalar.rs, src/tags/if_block.rs
=>  fix(value): Address undefined behavior 

src/parser.rs
No idea what tests I could create to test this. However, I did `cargo fmt` (on just this file, not all of them), `rustup run nightly cargo clippy`, and `cargo test`, and everything's green that was green before.
=> Fixes #345

liquid-bin/Cargo.toml, liquid-bin/src/main.rs, liquid-compiler/src/lib.rs, liquid-error/Cargo.toml, liquid-error/src/clone.rs, liquid-error/src/error.rs, liquid-error/src/lib.rs, liquid-help-md/Cargo.toml, liquid-help-md/src/lib.rs, liquid-interpreter/Cargo.toml, liquid-interpreter/src/context.rs, liquid-interpreter/src/expression.rs, liquid-interpreter/src/lib.rs, liquid-interpreter/src/renderable.rs, liquid-interpreter/src/stack.rs, liquid-interpreter/src/store.rs, liquid-interpreter/src/template.rs, liquid-interpreter/src/variable.rs, liquid-value/Cargo.toml, liquid-value/src/lib.rs, liquid-value/src/map.rs, liquid-value/src/path.rs, liquid-value/src/scalar.rs, liquid-value/src/ser.rs, liquid-value/src/values.rs, liquid-value/tests/value.rs, tests/conformance_ruby/standard_filter_test.rs
- Had problems with pest for the compiler
- Had problems with liquid-derive in liquid
=> refactor: Switch to 2018 edition

azure-pipelines.yml, liquid-derive/src/filter_parameters.rs, liquid-value/src/scalar.rs, src/filters/extra/date.rs, src/filters/std/date.rs, src/filters/std/html.rs, src/filters/std/string/case.rs, tests/conformance_ruby/standard_filter_test.rs, tests/derive_macros.rs, tests/derive_macros_test_filters/mixed.rs, tests/test_helper.rs
=> Add support for a date only type

liquid-compiler/src/block.rs, liquid-compiler/src/filter.rs, liquid-compiler/src/registry.rs, liquid-compiler/src/tag.rs, src/parser.rs, src/tags/assign_tag.rs, src/tags/capture_block.rs, src/tags/case_block.rs, src/tags/comment_block.rs, src/tags/cycle_tag.rs, src/tags/for_block.rs, src/tags/if_block.rs, src/tags/ifchanged_block.rs, src/tags/include_tag.rs, src/tags/increment_tags.rs, src/tags/interrupt_tags.rs, src/tags/raw_block.rs
=> refactor: Relax `'static` lifetime on reflection

crates/interpreter/src/store.rs, crates/value/src/map.rs, crates/value/src/scalar.rs, crates/value/src/values.rs, src/filters/std/html.rs, src/parser.rs, src/reflection.rs
These were found when trying to convert to traits.
BREAKING CHANGE: Misc unused functions were removed
=> fix(value): Remove extraneous parts of the API

crates/value/src/values.rs, tests/test_helper.rs
BREAKING CHANGE: Some limits with making `Value` a type alias.
=> feat(value): Support a ValueCow

Cargo.toml, src/filters/jekyll/slugify.rs, src/filters/std/html.rs, src/filters/std/url.rs, src/lib.rs
=> chore: Transition to once_cell

crates/value/src/scalar.rs, crates/value/src/values.rs
BREAKING CHANGE: Before, they describe the whether they were the symbol.
Now they describe if they were matched with the symbols.
=> refactor(value): Swithc role of is_empty / is_blank

crates/compiler/src/parser.rs, crates/value/src/lib.rs, crates/value/src/scalar.rs, crates/value/src/state.rs, crates/value/src/values.rs, src/filters/std/array.rs, src/filters/std/mod.rs, src/tags/for_block.rs, src/tags/if_block.rs
This will make it easier to add a Value trait
=> refactor(value): Change how we track value state

crates/value/src/values.rs
=> fix(value): Restore `as_object_mut` needed in Cobalt

crates/value/src/macros.rs, crates/value/src/map.rs, crates/value/src/ser.rs, crates/value/src/values.rs, tests/conformance_ruby/assign_test.rs, tests/conformance_ruby/blank_test.rs, tests/conformance_ruby/filter_test.rs, tests/conformance_ruby/output_test.rs, tests/conformance_ruby/parsing_quirks_test.rs, tests/conformance_ruby/standard_filter_test.rs, tests/conformance_ruby/tags/break_tag_test.rs, tests/conformance_ruby/tags/continue_tag_test.rs, tests/conformance_ruby/tags/for_tag_test.rs, tests/conformance_ruby/tags/if_else_tag_test.rs, tests/conformance_ruby/tags/include_tag_test.rs, tests/conformance_ruby/tags/increment_tag_test.rs, tests/conformance_ruby/tags/standard_tag_test.rs, tests/conformance_ruby/tags/statements_test.rs, tests/conformance_ruby/tags/table_row_test.rs, tests/conformance_ruby/tags/unless_else_tag_test.rs, tests/conformance_ruby/template_test.rs, tests/conformance_ruby/variable_test.rs, tests/test_helper.rs
=> Revamp value macros

Cargo.toml, benches/handlebars_liquid.rs, benches/tera_bigcontext_liquid.rs, benches/tera_template_liquid.rs
=> fix(benches): Get benches runniung again

crates/derive/Cargo.toml, crates/derive/src/filter_parameters.rs, crates/derive/src/parse_filter/mod.rs
=> chore: Update derive deps

Cargo.toml, crates/derive/src/lib.rs, crates/derive/src/object_view.rs, crates/derive/src/value_view.rs, crates/value/src/object.rs, src/lib.rs, tests/derive_object.rs
=> Derive macros for ObjectView / ValueView

crates/compiler/src/parser.rs, crates/derive/src/filter/display.rs, crates/derive/src/filter/from_filter_parameters.rs, crates/derive/src/filter_parameters.rs, crates/derive/src/helpers.rs, crates/derive/src/parse_filter/filter_reflection.rs, crates/derive/src/parse_filter/mod.rs, crates/derive/src/parse_filter/parse_filter.rs, crates/error/src/error.rs, crates/error/src/result_ext.rs, crates/help-md/src/lib.rs, crates/interpreter/src/stack.rs, crates/value/src/ser.rs, crates/value/src/view.rs, src/partials/lazy.rs
=> Address clippy

crates/bin/Cargo.toml, crates/bin/LICENSE-APACHE, crates/bin/LICENSE-MIT, crates/bin/README.md, crates/core/Cargo.toml, crates/core/LICENSE-APACHE, crates/core/LICENSE-MIT, crates/core/README.md, crates/derive/Cargo.toml, crates/derive/LICENSE-APACHE, crates/derive/LICENSE-MIT, crates/derive/README.md, crates/error/Cargo.toml, crates/error/LICENSE-APACHE, crates/error/LICENSE-MIT, crates/error/README.md, crates/kstring/LICENSE-APACHE, crates/kstring/LICENSE-MIT
All contributors to liquid-error have approved.
johannhof last contributed 8ffb4c85da843e4bb9f463667328446d74e326a9 and
these were created after that by goncalerta and myself with contributions by others.
See #7
=> fix: Re-license error, core, bin, derive

CHANGELOG.md, crates/lib/src/jekyll/include_tag.rs, crates/lib/src/stdlib/tags/include_tag.rs, tests/conformance_ruby/tags/include_tag_test.rs
=> Fixup includes to better conform

crates/lib/src/stdlib/filters/string/truncate.rs, tests/conformance_ruby/standard_filter_test.rs
=> fix(std): Overflow in `truncate`

crates/lib/src/stdlib/filters/math.rs, tests/conformance_ruby/standard_filter_test.rs
=> fix(std): Divide by zero should error, not panic

crates/lib/Cargo.toml, crates/lib/src/stdlib/filters/url.rs
=> chore: Use a smaller dependency

crates/lib/Cargo.toml, crates/lib/src/stdlib/filters/url.rs
=> chore: Upgrade percent_encoding

CHANGELOG.md, crates/lib/src/stdlib/filters/date.rs
=> fix(lib): Don't crash on date formats

crates/core/src/model/scalar/mod.rs
=> feat(value): Support more numeric types

crates/core/src/model/ser.rs, crates/core/src/model/value/mod.rs, crates/core/src/model/value/ser.rs
This is useful for dealing with foreign plugins, like Sql, Lua, etc.
=> feat(model): Support converting from ValueView

src/parser.rs
=> feat(liquid): Add where to std filters

CHANGELOG.md, crates/lib/src/extra/date.rs
=> fix(lib): Get to compile

crates/lib/src/stdlib/blocks/for_block.rs, tests/conformance_ruby/tags/for_tag_test.rs
fixes #294 
I added a test in addition to removing the expected panic attribute on the conformance test, let me know if I missed anything.
=> feat(lib): Allow for-loop over `nil`

azure-pipelines.yml
=> fix(ci): Ensure stable results

azure-pipelines.yml, crates/core/Cargo.toml, crates/core/src/model/scalar/mod.rs, crates/core/src/model/value/ser.rs, crates/core/src/model/value/values.rs, crates/core/src/runtime/runtime.rs, crates/core/src/runtime/variable.rs, crates/derive/src/filter/from_filter_parameters.rs, crates/lib/Cargo.toml, crates/lib/src/stdlib/filters/array.rs, crates/lib/src/stdlib/filters/math.rs, crates/lib/src/stdlib/filters/string/case.rs, crates/lib/src/stdlib/tags/include_tag.rs, crates/lib/tests/test_helper.rs, tests/conformance_ruby/assign_test.rs, tests/conformance_ruby/blank_test.rs, tests/conformance_ruby/capture_test.rs, tests/conformance_ruby/error_handling_test.rs, tests/conformance_ruby/output_test.rs, tests/conformance_ruby/standard_filter_test.rs, tests/derive_macros.rs, tests/derive_macros_test_filters/mixed.rs, tests/derive_object.rs, tests/filters.rs, tests/fixtures.rs, tests/multithreading.rs, tests/test_helper.rs
=> chore: Update crate

crates/lib/src/stdlib/blocks/for_block.rs
This builds on #431 to reduce copying expensive data.
The structure of `core::model` unfortunately isn't providing an
opportunity to do the same for iterating on objects.
=> perf(stdlib): Don't copy data when looping on arrays

CHANGELOG.md, benches/handlebars.rs, benches/liquid.rs, benches/tera_bigcontext.rs, benches/tera_template.rs, benches/tera_tera.rs
=> test(perf): Improve value of output

crates/core/Cargo.toml, crates/core/src/partials/inmemory.rs, crates/core/src/runtime/runtime.rs, crates/lib/src/stdlib/filters/mod.rs, crates/lib/src/stdlib/filters/slice.rs, tests/conformance_ruby/parse_tree_visitor_test.rs, tests/derive_macros_test_filters/mixed.rs, typos.toml
BREAKING-CHANGE: In one place we do an `Into` to an `anymap` type.  This
is unlikely to break anyone.
Fixes #440
=> chore!: Switch to anymap2

crates/core/src/partials/lazy.rs
This PR makes `LazyStore` add the parsed `Arc<dyn Renderable>` to its cache when `get_or_create()` or `try_get_or_create()` are called. This PR also adds regression tests that make sure a call to `LazyStore::get()` or `LazyStore::try_get()` adds the parsed partial to its cache.
This PR fixes #450.
=> fix(liquid-lib): Make LazyStore cache parsed partials

Cargo.toml, README.md
=> docs: Update README

crates/bin/Cargo.toml, crates/bin/src/main.rs
=> chore: Upgrade to clap3

Cargo.toml, crates/bin/Cargo.toml, crates/bin/README.md, crates/core/Cargo.toml, crates/core/README.md, crates/derive/Cargo.toml, crates/derive/README.md, crates/help-md/Cargo.toml, crates/help-md/README.md, crates/lib/Cargo.toml, crates/lib/README.md, src/lib.rs
Version reference in lib.rs was outdated.
=> docs: Correct version references

crates/core/Cargo.toml
Somehow I missed this previously.
=> fix!: Actually upgrade kstring

crates/core/src/model/find.rs, crates/core/src/model/scalar/datetime/strftime.rs, crates/core/src/model/value/values.rs, crates/core/src/parser/parser.rs, crates/lib/src/stdlib/tags/cycle_tag.rs, tests/conformance_ruby/blank_test.rs, tests/multithreading.rs
=> style: Make clippy happy

crates/core/src/model/scalar/datetime.rs
Hi,
Since this [PR](https://github.com/cobalt-org/liquid-rust/pull/494) the date format in serde require milliseconds, this break the downstream project cobalt, that if updated require the dates in the frontmatter to have the milliseconds in the published_date, this PR correct that problem having the support of parsing both dates with and without milliseconds, and optionally include the milliseconds in serialization in case are a value != 0.
=> fix: Correct date time serde formats

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/main.rs
=> chore: Upgrade clap

Cargo.lock, Cargo.toml, crates/bin/Cargo.toml, crates/core/Cargo.toml, crates/derive/Cargo.toml, crates/derive/src/filter/display.rs, crates/derive/src/filter/from_filter_parameters.rs, crates/derive/src/filter_parameters.rs, crates/derive/src/helpers.rs, crates/derive/src/object_view.rs, crates/derive/src/parse_filter/mod.rs, crates/derive/src/value_view.rs
=> chore(derive): Update to syn v2

README.md
Use https:// and use URL that it redirects to
=> Update URL for Liquid

Cargo.lock, Cargo.toml, crates/core/Cargo.toml
=> chore: Update snapbox

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/model/value/ser.rs, tests/fixtures.rs, tests/multithreading.rs, tests/parse_file.rs, tests/syntax.rs
=> chore: Upgrade to snapbox 0.6

src/lib.rs, src/partials.rs
- [N/A] Tests created for any new feature or regression tests for bugfixes.
#509
=> Add documentation snippet for using partials

Cargo.toml
~~- [ ] Tests created for any new feature or regression tests for bugfixes.__~~
=> Fixed changelog URL.

crates/core/src/parser/parser.rs, tests/errors.rs
=> fix(parser): Correctly bind 'char' boundaries

README.md
Hi!
I created Mandy many months ago and decided to rewrite the entire thing from scratch to be
- faster and lighter
- easier to maintain
- work on all major platforms
- have a significantly lighter codebase
The new version of Mandy uses the crate for Liquid but compared to the previous version, Mandy shrunk from around 4300 lines to around 1700 lines. Also went through a rebranding which is why I have a new name and new handle now. 
@epage If you see this, you will remember (probably).
=> Updated the link to Mandy.

README.md, src/lib.rs, src/partials.rs
=> mut is not needed in these examples
